### ISSUE TITLE
Feture request: Ability to rearrange the order currency is displayed

### ISSUE THREAD

**Issue by Ponsari** [cstby/foundryvtt-world-currency-5e#19]
Being locked to the 2nd highest currency as the default currency is really limiting when it comes to custom coins unless you're willing to manually convert every single item. Simply allowing the order in which the different currencies are displayed on the sheet would give a lot more freedom (even if we're still limited to 5), and it would allow to set up things such as "Silver Standard" or editing prices much more easily.
PS: your "submit an issue" link gives a 404. It's missing the "foundryvtt-" part.

**Comment by cstby** [comment]
Thanks for pointing out the broken link! That'll be fixed in the next release.

I agree about being locked in to the 2nd highest currency. I'd like to hear more about the end result you're trying to achieve.

As far as implementation, all DND5E items are priced only in terms of Gold Pieces. In version World Currency 5e 2.0, I've allowed users to define their conversion rates in terms of Gold Pieces. That effectively allows you to rearrange currencies (putting more valuable ones further to right). It also allows you avoid having any of your currencies 1:1 with gold. For example, you can have a "silver only" setup where you hide all currencies except for silver and set silver's conversion rate to 10.

**Comment by Ponsari** [comment]
The end result is simple: There are plenty of items that cost 1000gp or more, so I have set up 2 coin denominations that are larger than gp: the UP (=50gp) and the DP (=40up). This gives me 2 choices:
a) I come to terms with it and let the sheet show currencies in this order: DP - GP - UP - SP - CP.
b) I change the denominations, which means that every price for every one of my 250+ items is wrong, so I have to manually change each and every one of them.
This means that technically this functionally is already possible. But it's a pain either way, and I can see how other people could have some trouble wrapping their heads around all the weird permutations you need to do to make several of the changes one would expect to make when making custom coinage.
PS: The module.json file doesn't conform to the v10 formatting. It's fine for now, but please do look into updating it:
![image](https://user-images.githubusercontent.com/54489177/199242591-9f482f52-69a1-4f1d-bf86-9c035f0eb23b.png)

**Comment by cstby** [comment]
Given your end result, I'd try setting it up this way. 
- change pp to dp and set the conversion to 0.005
- change gp to up and set the conversion to 0.02
- change ep to gp and set the conversion rate to 1
- set sp conversion rate to 10
- set cp conversion rate to 100

I believe that sets everything up how you want without any drawbacks. Try it out and let me know if that's right?

**Comment by cstby** [comment]
I believe this issue was resolved, so I'm closing it out.
